$('#tradeTab > div:nth-child(3) > div > input').keyup(function() {
  let amount = parseFloat($(this).val());
  let order = JSON.parse(localStore.getItem("tradeableOrder"));
  let tokenName = $('#tradeTab > div:nth-child(1) > select').val();
  let element = $('option[name="' + tokenName + '"]');
  let tokenAddress = element.attr("address");
  let amountA = parseFloat(order.limitTokenA);
  let amountB = parseFloat(order.limitTokenB);
  let price = (amountB/amountA).toFixed(2);
  price = tokenAddress === order.tokenA ? (amount*(1/price)).toFixed(2) : (amount*price);
  let baseToken = order.tokenA;
  let baseTokenName = $('option[address="' + baseToken + '"]').attr('name');
  let tradedToken = order.tokenB;
  let tradedTokenName = $('option[address="' + tradedToken + '"]').attr('name');
  let base,traded;
  tokenAddress === order.tokenA ? (base = tradedTokenName,traded = baseTokenName) : (traded = tradedTokenName,base = baseTokenName);
  console.log(tokenAddress === order.tokenA, base,traded);
  $('#tradeTab > div.total > div > div:nth-child(1) > div.col-md-4 > p').text(base);
  $('#tradeTab > div.total > div > div:nth-child(2) > div.col-md-4 > p').text(traded);
  $('#tradeTab > div.total > div > div:nth-child(1) > div.col-md-8 > span').text(amount);  
  $('#tradeTab > div.total > div > div:nth-child(2) > div.col-md-8 > span').text(price);
});  
